feat: update aliasrc with new aliases and environment settings; update subproject commits for linutils and winutils

diff --git a/configs/aliasrc b/configs/aliasrc
--- a/configs/aliasrc
+++ b/configs/aliasrc
@@ -1,27 +1,31 @@
-#
-# # ex - archive extractor
-# # usage: ex <file>
-ex ()
-{
-  if [ -f $1 ] ; then
-    case $1 in
-      *.tar.bz2)   tar xjf $1   ;;
-      *.tar.gz)    tar xzf $1   ;;
-      *.tar.xz)    tar xJf $1   ;;
-      *.bz2)       bunzip2 $1   ;;
-      *.rar)       unrar x $1     ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1   ;;
-      *.tgz)       tar xzf $1   ;;
-      *.zip)       unzip $1     ;;
-      *.Z)         uncompress $1;;
-      *.7z)        7z x $1      ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
-  fi
+#------------------------------------------------------------------------------
+# Environment Settings
+#------------------------------------------------------------------------------
+export EDITOR='nano'
+
+#------------------------------------------------------------------------------
+# File Extraction Function
+#------------------------------------------------------------------------------
+ex () {
+    if [ -f $1 ] ; then
+        case $1 in
+            *.tar.bz2)   tar xjf $1   ;;
+            *.tar.gz)    tar xzf $1   ;;
+            *.tar.xz)    tar xJf $1   ;;
+            *.bz2)       bunzip2 $1   ;;
+            *.rar)       unrar x $1   ;;
+            *.gz)        gunzip $1    ;;
+            *.tar)       tar xf $1    ;;
+            *.tbz2)      tar xjf $1   ;;
+            *.tgz)       tar xzf $1   ;;
+            *.zip)       unzip $1     ;;
+            *.Z)         uncompress $1 ;;
+            *.7z)        7z x $1      ;;
+            *)          echo "'$1' cannot be extracted via ex()" ;;
+        esac
+    else
+        echo "'$1' is not a valid file"
+    fi
 }
 
 export EDITOR='nano' 
@@ -29,15 +33,19 @@ export EDITOR='nano'
 netrestart() { sudo systemctl restart systemd-networkd.service && C=$(nmcli c show --active | awk 'FNR == 2 {print $1}') && nmcli down $C && nmcli c up $C }
 
 alias pacman-update='sudo pacman-mirrors --geoip'
+alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
+alias sysupdate='sudo pacman -Sy archlinux-keyring --noconfirm && yay'
 
+#------------------------------------------------------------------------------
+# File Operations
+#------------------------------------------------------------------------------
+# Basic ls aliases
 alias ls='ls --color=auto'
-alias ll='ls -l'
-# ls, the common ones I use a lot shortened for rapid fire usage
-alias l='ls -lFh'     #size,show type,human readable
-alias la='ls -lAFh'   #long list,show almost all,show type,human readable
-alias lr='ls -tRFh'   #sorted by date,recursive,show type,human readable
-alias lt='ls -ltFh'   #long list,sorted by date,show type,human readable
-alias ll='ls -l'      #long list
+alias l='ls -lFh'        # size,show type,human readable
+alias la='ls -lAFh'      # long list,show almost all,show type,human readable
+alias lr='ls -tRFh'      # sorted by date,recursive,show type,human readable
+alias lt='ls -ltFh'      # long list,sorted by date,show type,human readable
+alias ll='ls -l'         # long list
 alias ldot='ls -ld .*'
 alias lS='ls -1FSsh'
 alias lart='ls -1Fcart'
@@ -80,20 +88,40 @@ alias mv='mv -i'
 alias vim='vim'
 alias vi='vim'
 alias c='code-insiders'
-alias gds-start='sudo systemctl start openvpn-client@gds'
-alias gds-stop='sudo systemctl stop openvpn-client@gds'
+alias python='python3'
+alias pip='pip3'
+
+#------------------------------------------------------------------------------
+# Git Commands
+#------------------------------------------------------------------------------
+# Basic git aliases
+alias g='git'
+alias gst='git status'
+alias gl='git pull'
+alias gp='git push'
+alias gc='git commit -v'
+alias gca='git commit -v -a'
+alias gco='git checkout'
+alias gcm='git checkout master'
+alias gb='git branch'
+alias gba='git branch -a'
+alias ga='git add'
+alias gm='git merge'
+
+# Git helper functions
 gitpush() {
     git add .
     git commit -m "$*"
     git pull
     git push
 }
+
 gitupdate() {
     eval "$(ssh-agent -s)"
     ssh-add ~/.ssh/id_rsa
 }
 
-git_prune_local() { 
+git_prune_local() {
     local prune=$(git fetch -p ; git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d 2>&1)
     if [[ $prune =~ "not fully merged" ]]; then 
     echo -e "\nThere are some commits that need your attention, problably you should run:\n
@@ -108,100 +136,29 @@ git_prune_local() {
         esac
     done
     fi    
-    }
-
-    
-alias gp=gitpush
-alias gu=gitupdate
-alias lbrynet='/opt/LBRY/resources/static/daemon/lbrynet'
-alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
-
-alias sysupdate='sudo pacman -Sy archlinux-keyring --noconfirm && yay'
-alias python='python3'
-alias pip='pip3'
-alias wtor='webtorrent download -u 100 '
-alias obssync='rclone bisync gdrive:WORK/ /home/hypeit/Documents/obsidian/ --verbose --resync'
-alias sshp='sshpass -e ssh '
-
-
-# Aliases git
-alias g='git'
-compdef g=git
-alias gst='git status'
-compdef _git gst=git-status
-alias gl='git pull'
-compdef _git gl=git-pull
-alias gup='git fetch && git rebase'
-compdef _git gup=git-fetch
-alias gp='git push'
-compdef _git gp=git-push
-gdv() { 
-  git diff -w "$@" | view - 
 }
-compdef _git gdv=git-diff
-alias gc='git commit -v'
-compdef _git gc=git-commit
-alias gca='git commit -v -a'
-compdef _git gca=git-commit
-alias gco='git checkout'
-compdef _git gco=git-checkout
-alias gcm='git checkout master'
-alias gb='git branch'
-compdef _git gb=git-branch
-alias gba='git branch -a'
-compdef _git gba=git-branch
-alias gcount='git shortlog -sn'
-compdef gcount=git
-alias gcp='git cherry-pick'
-compdef _git gcp=git-cherry-pick
-alias glg='git log --stat --max-count=5'
-compdef _git glg=git-log
-alias glgg='git log --graph --max-count=5'
-compdef _git glgg=git-log
-alias gss='git status -s'
-compdef _git gss=git-status
-alias ga='git add'
-compdef _git ga=git-add
-alias gm='git merge'
-compdef _git gm=git-merge
-alias grh='git reset HEAD'
-alias grhh='git reset HEAD --hard'
-compdef _git grhh=git-reset-hard
-alias gsbm='git submodule update --init --remote --force --recursive'
-compdef _git gsbm='git-submodule-update'
 
-# Git and svn mix
-alias git-svn-dcommit-push='git svn dcommit && git push github master:svntrunk'
-compdef git-svn-dcommit-push=git
-
-alias gsr='git svn rebase'
-alias gsd='git svn dcommit'
-#
-# Will return the current branch name
-# Usage example: git pull origin $(current_branch)
-#
+# Git branch functions
 function current_branch() {
-  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
-  echo ${ref#refs/heads/}
+    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
+    echo ${ref#refs/heads/}
 }
 
 function current_repository() {
-
-  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
-  echo $(git remote -v | cut -d':' -f 2)
+    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
+    echo $(git remote -v | cut -d':' -f 2)
 }
 
-# these aliases take advantage of the previous function
-alias ggpull='git pull origin $(current_branch)'
-compdef ggpull=git
-alias ggpush='git push origin $(current_branch)'
-compdef ggpush=git
-alias ggpnp='git pull origin $(current_branch) && git push origin $(current_branch)'
-compdef ggpnp=git
+#------------------------------------------------------------------------------
+# Custom Tools and Utilities
+#------------------------------------------------------------------------------
+alias obssync='rclone bisync gdrive:WORK/ /home/hypeit/Documents/obsidian/ --verbose --resync'
+alias sshp='sshpass -e ssh '
+alias wtor='webtorrent download -u 100 '
+alias lbrynet='/opt/LBRY/resources/static/daemon/lbrynet'
+alias adbmount='adbfs -o kernel_cache -o rescan -o umask=0010 -o big_writes ~/droid'
 
-
-### Custom functions authored by mki
-
+# Instagram shortcode extractor
 function extract_shortcode() {
     if [ "$#" -ne 1 ]; then
         echo "Error: Invalid number of arguments. Please provide exactly one argument."
@@ -225,3 +182,5 @@ function extract_shortcode() {
 
     instaloader -- -${shortcode}
 }
+
+alias parurebuild='paru -Sy --rebuild --redownload --removemake --skipreview --noconfirm'
